version: 2

# HTML is always built, these are additional formats only
formats:
    - pdf

build:
    os: ubuntu-22.04
    tools:
        python: "3.12"
    apt_packages:
        - graphviz

python:
    install:
        - requirements: docs/Sphinx-guides/requirements.txt


sphinx:
    configuration: docs/Sphinx-guides/source/conf.py
    fail_on_warning: true