FROM alpine:3.15

WORKDIR /var/www/html

# When using Composer, disable the warning about running commands as root/super user
ENV COMPOSER_ALLOW_SUPERUSER=1  \
	SERVERNAME="localhost"      \
	HTTPS="on"                  \
	OJS_VERSION=3_3_0-0 \
	OJS_CLI_INSTALL="0"         \
	OJS_DB_HOST="localhost"     \
	OJS_DB_USER="ojs"           \
	OJS_DB_PASSWORD="ojs"       \
	OJS_DB_NAME="ojs"           \
	OJS_WEB_CONF="/etc/apache2/conf.d/ojs.conf"	\
	OJS_CONF="/var/www/html/config.inc.php"


# PHP_INI_DIR to be symmetrical with official php docker image
ENV PHP_INI_DIR /etc/php/7.4

# Basic packages
ENV PACKAGES 			\
	ca-certificates 	\
	curl 			\
	ttf-freefont		\
	dcron 			\
	patch			\
	php7			\
	runit

# PHP extensions
ENV PHP_EXTENSIONS		\
	php7-bcmath		\
	php7-bz2		\
	php7-calendar		\
	php7-ctype		\
	php7-curl		\
	php7-dom		\
	php7-exif		\
	php7-fileinfo		\
	php7-ftp		\
	php7-gettext		\
	php7-intl		\
	php7-iconv		\
    gnu-libiconv            \
	php7-json		\
	php7-mbstring		\
	php7-mysqli		\
	php7-opcache		\
	php7-openssl		\
	php7-pdo_mysql		\
	php7-phar		\
	php7-posix		\
	php7-session		\
	php7-shmop		\
	php7-simplexml		\
	php7-sockets		\
	php7-sysvmsg		\
	php7-sysvsem		\
	php7-sysvshm		\
	php7-tokenizer		\
	php7-xml		\
	php7-xmlreader		\
	php7-xmlwriter		\
	php7-zip		\
	php7-zlib

# Required to build OJS:
ENV BUILDERS 		\
	git 			\
	nodejs 			\
	npm

RUN set -xe \
	&& apk add --no-cache --virtual .build-deps $BUILDERS \
	&& apk add --no-cache $PACKAGES \
	&& apk add --no-cache $PHP_EXTENSIONS \
# Building OJS:
	# Configure and download code from git
	&& git config --global url.https://.insteadOf git:// \
	&& git config --global advice.detachedHead false \
	&& git clone --depth 1 --single-branch --branch $OJS_VERSION --progress https://github.com/pkp/ojs.git . \
	&& git submodule update --init --recursive >/dev/null \
	# Composer vudu:
 	&& curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer.phar \
	# To avoid timeouts with gitHub we use tokens:
	# TODO: Replace personal token by an official one.
 	# && composer.phar config -g github-oauth.github.com 58778f1c172c09f3add6cb559cbadd55de967d47 \
	# Install Composer Deps:
 	&& composer.phar --working-dir=lib/pkp install --no-dev \
 	&& composer.phar --working-dir=plugins/paymethod/paypal install --no-dev \
	&& composer.phar --working-dir=plugins/generic/citationStyleLanguage install --no-dev \
	# Node joins to the party:
	&& npm install -y && npm run build \
# Create directories
 	&& mkdir -p /var/www/files  \
	&& cp config.TEMPLATE.inc.php config.inc.php
